apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-nginx
  namespace: storens
spec:
  ingressClassName: nginx-internal
  rules:
  - host:
    http:
      paths:
      - backend:
          service:
            name: store-front
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-nginx
  namespace: httpbin
spec:
  ingressClassName: nginx-internal
  rules:
  - host:
    http:
      paths:
      - backend:
          service:
            name: httpbin
            port:
              number: 80
        path: /headers
        pathType: Prefix
